package com.ialogia.zerocloudassist.rag

import org.junit.Assert.assertEquals
import org.junit.Test

/** Tablas de RRF, presupuesto y prioridad del plan 02 (§5, E1), gemelas de `tools/tests/test_evaluar.py`. */
class ManualSearchTest {

    // Imitan los chunks reales: la entrada 2001 de alarmas va tras la cabecera de su tabla.
    private val texts = mapOf(
        1L to "3005 MOT THERM PROT\nSelects how the drive reacts (fault 0009).",
        2L to "Alarm messages generated by the drive\nCODE ALARM CAUSE WHAT TO DO\n2001 OVERCURRENT\nCheck.",
        3L to "2001 MINIMUM\nSPEED\nDefines the allowed minimum speed.",
        4L to "0009 MOT OVERTEMP\nMotor temperature estimation is too high.",
    )
    private val chapters = mapOf(
        1L to "Actual signals and parameters", 2L to "Fault tracing",
        3L to "Actual signals and parameters", 4L to "Fault tracing",
    )

    @Test
    fun `rrf fusiona por rango`() {
        // 1: 1/61 + 1/62; 3: 1/63 + 1/61; 2: 1/62
        assertEquals(listOf(1L, 3L, 2L), ManualSearch.rrf(listOf(listOf(1L, 2L, 3L), listOf(3L, 1L))))
    }

    @Test
    fun `rrf con una lista vacía`() {
        assertEquals(listOf(5L, 4L), ManualSearch.rrf(listOf(emptyList(), listOf(5L, 4L))))
    }

    @Test
    fun `select llena el presupuesto en orden`() {
        // 130 + 8 + 140 + 8 = 286 ≤ 300
        assertEquals(listOf(1L, 2L), ManualSearch.select(listOf(1L, 2L, 3L), mapOf(1L to 130, 2L to 140, 3L to 120)))
    }

    @Test
    fun `select salta el que no cabe y sigue`() {
        assertEquals(listOf(1L, 3L), ManualSearch.select(listOf(1L, 2L, 3L), mapOf(1L to 200, 2L to 150, 3L to 80)))
    }

    @Test
    fun `select descarta un chunk que no cabe solo`() {
        assertEquals(emptyList<Long>(), ManualSearch.select(listOf(1L), mapOf(1L to 320)))
    }

    @Test
    fun `prioritize pone primero la entrada que define el código`() {
        assertEquals(listOf(4L, 1L), ManualSearch.prioritize(listOf(1L, 4L), texts, chapters, listOf("0009"), null))
    }

    @Test
    fun `prioritize encuentra la entrada aunque no abra el chunk`() {
        assertEquals(listOf(2L, 1L), ManualSearch.prioritize(listOf(1L, 2L), texts, chapters, listOf("2001"), null))
    }

    @Test
    fun `prioritize desempata por el capítulo preferido`() {
        assertEquals(listOf(3L, 2L), ManualSearch.prioritize(listOf(3L, 2L), texts, chapters, listOf("2001"), null))
        assertEquals(
            listOf(2L, 3L),
            ManualSearch.prioritize(listOf(3L, 2L), texts, chapters, listOf("2001"), "Fault tracing"),
        )
    }

    @Test
    fun `prioritize sin términos no cambia el orden`() {
        assertEquals(
            listOf(3L, 1L, 2L),
            ManualSearch.prioritize(listOf(3L, 1L, 2L), texts, chapters, emptyList(), "Fault tracing"),
        )
    }

    @Test
    fun `cosineTopK devuelve los índices por similitud`() {
        // Vectores de dimensión 2 con norma 1, en una sola lista plana.
        val vectors = floatArrayOf(1f, 0f, 0f, 1f, 0.6f, 0.8f)
        assertEquals(listOf(1, 2, 0), ManualSearch.cosineTopK(floatArrayOf(0f, 1f), vectors, dim = 2, k = 3))
        assertEquals(listOf(1, 2), ManualSearch.cosineTopK(floatArrayOf(0f, 1f), vectors, dim = 2, k = 2))
    }
}
