"""Tablas de RRF y presupuesto del plan 02 (§5, E1). La misma tabla va en ManualSearchTest.kt."""

from zca_tools.evaluar import acierta, priorizar, rrf, seleccionar

# Imitan los chunks reales: la entrada 2001 de alarmas va tras la cabecera de su tabla.
TEXTOS = {
    1: "3005 MOT THERM PROT\nSelects how the drive reacts (fault 0009).",
    2: "Alarm messages generated by the drive\nCODE ALARM CAUSE WHAT TO DO\n2001 OVERCURRENT\nCheck.",
    3: "2001 MINIMUM\nSPEED\nDefines the allowed minimum speed.",
    4: "0009 MOT OVERTEMP\nMotor temperature estimation is too high.",
}
CAPITULOS = {1: "Actual signals and parameters", 2: "Fault tracing",
             3: "Actual signals and parameters", 4: "Fault tracing"}


def test_rrf_fusiona_por_rango():
    # 1: 1/61 + 1/62; 3: 1/63 + 1/61; 2: 1/62
    assert rrf([[1, 2, 3], [3, 1]]) == [1, 3, 2]


def test_rrf_con_una_lista_vacia():
    assert rrf([[], [5, 4]]) == [5, 4]


def test_seleccionar_llena_el_presupuesto_en_orden():
    # 130 + 8 + 140 + 8 = 286 ≤ 300
    assert seleccionar([1, 2, 3], {1: 130, 2: 140, 3: 120}) == [1, 2]


def test_seleccionar_salta_el_que_no_cabe_y_sigue():
    assert seleccionar([1, 2, 3], {1: 200, 2: 150, 3: 80}) == [1, 3]


def test_seleccionar_descarta_un_chunk_que_no_cabe_solo():
    assert seleccionar([1], {1: 320}) == []


def test_priorizar_pone_primero_la_entrada_que_define_el_codigo():
    assert priorizar([1, 4], TEXTOS, CAPITULOS, ["0009"], None) == [4, 1]


def test_priorizar_encuentra_la_entrada_aunque_no_abra_el_chunk():
    assert priorizar([1, 2], TEXTOS, CAPITULOS, ["2001"], None) == [2, 1]


def test_priorizar_desempata_por_el_capitulo_preferido():
    assert priorizar([3, 2], TEXTOS, CAPITULOS, ["2001"], None) == [3, 2]  # orden estable
    assert priorizar([3, 2], TEXTOS, CAPITULOS, ["2001"], "Fault tracing") == [2, 3]


def test_priorizar_sin_terminos_no_cambia_el_orden():
    assert priorizar([3, 1, 2], TEXTOS, CAPITULOS, [], "Fault tracing") == [3, 1, 2]


def test_acierta_si_alguna_pagina_esperada_esta_entre_las_devueltas():
    assert acierta([360, 362], [362])
    assert acierta([18, 183], [183, 18])
    assert not acierta([359, 361], [362])
    assert not acierta([], [362])
